name: Test Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 12 * * *' # run at UTC noon

jobs:
  build-all-targets:
    strategy:
      matrix:
        include:
          - target: 'native'
            optimizaton: 'Debug'
          - target: 'native'
            optimizaton: 'ReleaseSafe'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Check formatting
        run:  |
          zig fmt --check .

      - name: Build and Run Demo
        run: |
          zig build -Doptimize=${{ matrix.optimizaton }} run

      - name: Build and Run Unit Tests
        run: |
          zig build -Doptimize=${{ matrix.optimizaton }} test --summary all
